export const ADD_HISTORY = 'ADD_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';

export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_COLOR_SCHEME = 'CHANGE_COLOR_SCHEME';

export const START_TRAINING = 'START_TRAINING';
export const FINISH_TRAINING = 'FINISH_TRAINING';
export const CHANGE_POSITION = 'CHANGE_POSITION';
