export const ADD_HISTORY = 'ADD_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_COLOR_SCHEME = 'CHANGE_COLOR_SCHEME';

export const START_TRAINING = 'START_TRAINING';
export const FINISH_TRAINING = 'FINISH_TRAINING';
export const CHANGE_POSITION = 'CHANGE_POSITION';

export const CHANGE_MAX_SPEED = 'CHANGE_MAX_SPEED';
export const CHANGE_LONGEST_DISTANCE = 'CHANGE_LONGEST_DISTANCE';

